# Generated by Django 5.0.1 on 2024-01-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=255)),
            ],
        ),
    ]
