version: '3'

services:
  frontend:
    build:
      context: ./frontend
    # ports:
    #   - "4200:80"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build:
      context: ./backend
    # ports:
    #   - "8000:8000"
    environment:
      - BACKEND_DB_HOST=db
      - BACKEND_DB_PORT=5432
      - BACKEND_DB_NAME=mydatabase
      - BACKEND_DB_USERNAME=myuser
      - BACKEND_DB_PASSWORD=mypassword
    depends_on:
      - db
    networks:
      - my-network

  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./nginx/ssl/private.key:/etc/nginx/ssl/server.key
    depends_on:
      - backend
      - frontend
    networks:
      - my-network

  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - my-network

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0        
    command: start-dev
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin      
    ports:      
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    networks:
      - my-network
networks:
  my-network:
    driver: bridge

