# Generated by Django 5.0.1 on 2024-01-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=255),
        ),
    ]
